name = "NCPlots"
uuid = "bb7f0a92-8966-4c85-beb0-c371d13b1908"
authors = ["Roel Stappers <roels@met.no> and contributors"]
version = "1.0.0-DEV"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
