name = "NCPlots"
uuid = "bb7f0a92-8966-4c85-beb0-c371d13b1908"
authors = ["Roel Stappers <roels@met.no> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
